version: '3.9'

services:

    ####################################################################################################
    # PHP
    ####################################################################################################
    php:
        container_name: laravel_php
        build: .docker/php
        ports:
            - 5173:5173
        volumes:
            - .:/var/www:cached
        networks:
            - ai-backend
    ####################################################################################################
    # Nginx
    ####################################################################################################
    nginx:
        container_name: laravel_nginx
        image: nginx
        ports:
            - 90:80
        volumes:
            - .:/var/www
            - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - php
        networks:
            - ai-backend
    ####################################################################################################
    # DATABASE (MySQL)
#    ####################################################################################################
#    db:
#        container_name: laravel_mysql
#        image: mysql:8.1
#        ports:
#            - 3396:3306
#        volumes:
#            - mysqlaibackend:/var/lib/mysql
#            - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#        environment:
#            MYSQL_ROOT_PASSWORD: root
#            MYSQL_DATABASE: laravel_db_name
#            MYSQL_USER: laravel_db_user
#            MYSQL_PASSWORD: laravel_db_pass
#        networks:
#            - ai-backend
     ####################################################################################################
     # DATABASE (MariaDB)
     ####################################################################################################
    db:
        container_name: laravel_mariadb
        image: mariadb:10.11
        ports:
         - 3386:3306
        volumes:
         - mysqlaibackend:/var/lib/mysql
#         - .docker/logs:/var/log/mysql
         - .docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
#         - .docker/db/sql:/docker-entrypoint-initdb.d
        environment:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: laravel_db_name
         MYSQL_USER: laravel_db_user
         MYSQL_PASSWORD: laravel_db_pass
        networks:
         - ai-backend
    ####################################################################################################
    # Mailpit
    ####################################################################################################
    mail:
        container_name: laravel_mailpit
        image: axllent/mailpit:latest
        ports:
        - 8025:8025
        - 1025:1025
        networks:
            - ai-backend

# Volumes
volumes:
    mysqlaibackend:
        driver: local

#Networks
networks:
    ai-backend:
        driver: bridge
